pipeline {
    agent { label 'linuxgitaws' }
    
    options {
        timestamps()
    }
    
    environment {
        GIT_REPO = 'https://github.com/varun-1515/git-maven.git'
        BRANCH = 'main'
	MAVEN_HOME = tool 'Maven3'
	JAVA_HOME = tool 'openjdk21'
	PATH = "${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${env.PATH}"
    }
    
    stages {
        stage('Checkout repo') {
            steps {
                git branch: BRANCH,
                    url: GIT_REPO,
                    credentialsId: '079e68d6-b157-4e64-b109-21d6085c3483'
            }
        }
        stage('Build') {
            steps {
                echo 'Running maven build...'
                sh '''
		    cd maven
                    mvn clean package
                '''
            }
        }
        stage('Unit Tests') {
            steps {
                sh '''
		    cd maven
                    mvn test
                '''
            }
            post {
                always {
		    junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
                }
            }
        }
    }
}

